#!/usr/bin/env python3
"""Run the whole analysis and write every output to outputs/.

    python run_pipeline.py

Invoked by `make pipeline`. Assumes the database exists; the Makefile runs
load_data.py first so the two steps stay visible as separate commands.

Writes:
    outputs/part2_cell_frequencies.csv          Part 2 summary table
    outputs/part2_population_summary.csv        mean, sd and range per population
    outputs/part2_composition.png               stacked composition, all samples
    outputs/part2_population_distributions.png  frequency spread per population
    outputs/part3_responder_statistics.csv      the significance table
    outputs/part3_responder_frequencies.csv     the rows the tests ran on
    outputs/part3_responder_boxplot.png         the boxplot Part 3 asks for
    outputs/part4_baseline_cohort.csv           the filtered baseline samples
    outputs/part4_counts_by_project.csv         samples and subjects per project
    outputs/part4_counts_by_response.csv        responders and non-responders
    outputs/part4_counts_by_sex.csv             males and females
    outputs/summary.md                           findings in prose
    report.html                                  the static dashboard snapshot
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pandas as pd

import analysis as an
import figures as fx
import plots

ROOT = Path(__file__).resolve().parent
OUTPUTS = ROOT / "outputs"
DOCS = ROOT / "docs"


def step(n: int, text: str) -> None:
    print(f"[{n}/6] {text}", flush=True)


def write_csv(df: pd.DataFrame, name: str) -> None:
    path = OUTPUTS / name
    df.to_csv(path, index=False)
    print(f"      {path.relative_to(ROOT)}  ({len(df)} rows)")


def main() -> int:
    OUTPUTS.mkdir(exist_ok=True)

    conn = an.connect()
    try:
        # -------------------------------------------------- Part 2
        step(1, "Part 2: relative frequency of each population in each sample")
        freq = an.frequency_table(conn)
        annotated = an.annotated_frequencies(conn)
        write_csv(freq, "part2_cell_frequencies.csv")

        order = fx.population_order(annotated)
        summary = (
            annotated.groupby("population")["percentage"]
            .agg(mean_pct="mean", sd="std", min_pct="min", max_pct="max")
            .reindex(order)
            .round(3)
            .reset_index()
        )
        summary.insert(1, "label", summary["population"].map(fx.label_of))
        write_csv(summary, "part2_population_summary.csv")

        # -------------------------------------------------- Part 3
        step(2, "Part 3: responders vs non-responders, melanoma miraclib PBMC")
        cohort = an.responder_comparison(conn)
        write_csv(cohort, "part3_responder_frequencies.csv")

        results = an.compare_responders(cohort, aggregate_by_subject=True)
        write_csv(results, "part3_responder_statistics.csv")

        sig = results.loc[results["significant"], "population"].tolist()
        if sig:
            print(f"      significant: {', '.join(fx.label_of(p) for p in sig)}")
        else:
            print("      significant: none after correction")

        # -------------------------------------------------- Part 4
        step(3, "Part 4: melanoma PBMC baseline samples from miraclib patients")
        base = an.baseline_cohort(conn)
        write_csv(base, "part4_baseline_cohort.csv")

        cuts = an.baseline_breakdown(base)
        write_csv(cuts["by_project"], "part4_counts_by_project.csv")
        write_csv(cuts["by_response"], "part4_counts_by_response.csv")
        write_csv(cuts["by_sex"], "part4_counts_by_sex.csv")
    finally:
        conn.close()

    # -------------------------------------------------- plots
    step(4, "Plots")
    for path in plots.write_all([OUTPUTS, DOCS]):
        print(f"      {path.relative_to(ROOT)}")

    # -------------------------------------------------- prose summary
    step(5, "Written summary")
    write_summary(summary, results, base, cuts, len(freq))
    print(f"      {(OUTPUTS / 'summary.md').relative_to(ROOT)}")

    # -------------------------------------------------- static report
    step(6, "Static HTML report")
    proc = subprocess.run(
        [sys.executable, "make_report.py"], cwd=ROOT, capture_output=True, text=True
    )
    if proc.returncode != 0:
        print(proc.stderr, file=sys.stderr)
        return 1
    print(f"      report.html")

    print("\nPipeline complete. Tables and plots are in outputs/.")
    return 0


def write_summary(summary, results, base, cuts, n_freq_rows) -> None:
    """Findings in prose, so a reader gets the answer without opening a CSV."""
    lines = [
        "# Results",
        "",
        "Generated by `run_pipeline.py`. Every number here traces to a CSV in this folder.",
        "",
        "## Part 2: relative frequencies",
        "",
        f"The summary table holds {n_freq_rows:,} rows, one per population per sample, "
        "in `part2_cell_frequencies.csv`. Percentages reconcile to 100 for every sample.",
        "",
        summary.to_markdown(index=False),
        "",
        "## Part 3: responders versus non-responders",
        "",
        "Melanoma, miraclib, PBMC only. Each subject's repeat samples are averaged "
        "before testing, so a subject counts once.",
        "",
        f"**Finding.** {fx.headline(results)}",
        "",
        results.drop(columns=["note"]).round(4).to_markdown(index=False),
        "",
        "Primary test is a two sided Mann-Whitney U. `p_value_adj` applies a "
        "Benjamini-Hochberg correction across the five populations and is the figure "
        "to quote. The Welch t-test is a cross-check. Cliff's delta reports how far "
        "the distributions are shifted, so a small p-value paired with a negligible "
        "delta can be flagged as thin.",
        "",
        "## Part 4: baseline cohort",
        "",
        f"{len(base)} samples from {base['subject'].nunique()} subjects, "
        f"melanoma PBMC at time zero, miraclib.",
        "",
        "### Samples and subjects per project",
        "",
        cuts["by_project"].to_markdown(index=False),
        "",
        "### By response",
        "",
        cuts["by_response"].to_markdown(index=False),
        "",
        "### By sex",
        "",
        cuts["by_sex"].to_markdown(index=False),
        "",
        "## Caveats",
        "",
        "- The five populations sum to 100 percent by construction, so one rising "
        "forces others down. A shift in monocytes and a shift in CD4 T cells are not "
        "independent findings.",
        "- This is an observational comparison inside a treated arm, so a separating "
        "population is a candidate biomarker rather than a mechanism.",
        "- Confirming either point needs a prespecified analysis on a held-out cohort.",
        "",
    ]
    (OUTPUTS / "summary.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
